### ISSUE TITLE
python 3 issues

### ISSUE THREAD

**Issue by TrustLak** [ratcave/natnetclient#3]
Hi,
Great work. I worked with natnet using python 2.7. It worked like a charm, so thanks alot. However, unlike what is mentioned in the readme file, it just did not work with python3. 

On the first run, an exception is raised from line 69 and stops the program. I tried commenting this out, but then I get other types of errors. For example:
line 248, in ping
     server_name = unpacked[0].split...
TypeError: a bytes-like object is required, not 'str'

I am trying to work around this by myself. It would be nice if you can give me some advice!

Thanks again!

**Comment by EndlessSmiling** [comment]
I try to use python 3.5, however, it gives me error below, when I connect the client, but it works for python 2.7
  ```
self.comm_sock = NatCommSocket(client_ip, comm_port)
  File "C:\Users\ezhou\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\natnetclient\natnet.py", line 82, in __init__
    super(NatCommSocket, self).__init__(client_ip, uPort, max_packet_size)
  File "C:\Users\ezhou\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\natnetclient\natnet.py", line 69, in __init__
    assert isinstance(max_packet_size/4, int), "max_packet_size must be divisible by 4"
AssertionError: max_packet_size must be divisible by 4
```

**Comment by nickdelgrosso** [comment]
Thanks!  I forgot to update this issue, but it's working for Python 3 issue now.
